# Generated by Django 3.1.2 on 2020-10-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('YUL', 'Montreal'), ('YYZ', 'Toronto'), ('YOW', 'Ottawa')], max_length=3)),
                ('airport', models.CharField(default='name of the airport', max_length=255)),
            ],
        ),
    ]
