# Generated by Django 3.1.2 on 2020-10-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='accronym',
            field=models.CharField(default='autofillaccronym', max_length=3),
        ),
    ]
