# Generated by Django 3.1.2 on 2020-10-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_airport_accronym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='accronym',
        ),
        migrations.AddField(
            model_name='airport',
            name='acronym',
            field=models.CharField(default='___', max_length=3),
        ),
    ]
